# Generated by Django 5.0.3 on 2024-04-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaLiga', models.CharField(max_length=200)),
                ('nrMaxEquipasDaLiga', models.IntegerField(default=10)),
                ('logoDaLiga', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=200)),
                ('nacionalidadeNome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaEquipa', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=10)),
                ('logoDaEquipa', models.CharField(default='', max_length=1000)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashscoreapp.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoJogador', models.CharField(max_length=200)),
                ('nrDoJogador', models.IntegerField()),
                ('dataDeNascimento', models.DateTimeField()),
                ('fotoDoJogador', models.CharField(default='', max_length=1000)),
                ('equipaDoJogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashscoreapp.equipa')),
                ('nacionalidadedoJogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashscoreapp.nacionalidade')),
            ],
        ),
    ]
