# Generated by Django 5.0.3 on 2024-05-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashscoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='liga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashscoreapp.liga'),
        ),
    ]
