# Generated by Django 5.0.3 on 2024-05-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashscoreapp', '0002_jogo_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipa',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='golos',
            field=models.IntegerField(default=0),
        ),
    ]
