# Generated by Django 5.0.3 on 2024-05-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashscoreapp', '0002_nacionalidade_bandeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaDoJogo', models.DateTimeField()),
                ('equipaDaCasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='flashscoreapp.equipa')),
                ('equipaDeFora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='flashscoreapp.equipa')),
            ],
        ),
    ]
