# Generated by Django 5.0.3 on 2024-05-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashscoreapp', '0003_jogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='nomeDoJogador',
        ),
    ]
