# Generated by Django 5.0.3 on 2024-05-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashscoreapp', '0003_equipa_pontos_jogador_golos'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='golosSofridos',
            field=models.IntegerField(default=0),
        ),
    ]
