# Generated by Django 5.0.3 on 2024-05-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashscoreapp', '0004_remove_jogador_nomedojogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='liga',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flashscoreapp.liga'),
        ),
    ]
