# Generated by Django 5.0.3 on 2024-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashscoreapp', '0005_remove_jogador_golossofridos_equipa_golos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='nomeDoJogador',
            field=models.CharField(default='Ronaldo', max_length=200),
        ),
    ]
